// Code generated by trpc-go/trpc-cmdline v1.0.8. DO NOT EDIT.
// source: logs.proto

package logs

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// LogServiceService defines service.
type LogServiceService interface {
	// Log Log says Log.
	Log(ctx context.Context, req *LogRequest) (*LogResponse, error)
}

func LogServiceService_Log_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LogRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LogServiceService).Log(ctx, reqbody.(*LogRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// LogServiceServer_ServiceDesc descriptor for server.RegisterService.
var LogServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "logs.LogService",
	HandlerType: ((*LogServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/logs.LogService/Log",
			Func: LogServiceService_Log_Handler,
		},
	},
}

// RegisterLogServiceService registers service.
func RegisterLogServiceService(s server.Service, svr LogServiceService) {
	if err := s.Register(&LogServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("LogService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedLogService struct{}

// Log Log says Log.
func (s *UnimplementedLogService) Log(ctx context.Context, req *LogRequest) (*LogResponse, error) {
	return nil, errors.New("rpc Log of service LogService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// LogServiceClientProxy defines service client proxy
type LogServiceClientProxy interface {
	// Log Log says Log.
	Log(ctx context.Context, req *LogRequest, opts ...client.Option) (rsp *LogResponse, err error)
}

type LogServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewLogServiceClientProxy = func(opts ...client.Option) LogServiceClientProxy {
	return &LogServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *LogServiceClientProxyImpl) Log(ctx context.Context, req *LogRequest, opts ...client.Option) (*LogResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/logs.LogService/Log")
	msg.WithCalleeServiceName(LogServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("LogService")
	msg.WithCalleeMethod("Log")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LogResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
